name: Unit tests

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

permissions:
    contents: read
    pull-requests: write

concurrency: 
    group: unit-tests-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            -   name: Set up JDK 17
                uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Delete old comments
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                if: ${{ always() }}
                run: scripts/deleteOldComments.sh "test" "Unit" ${{github.event.number}}
            -   name: Run unit tests with coverage
                uses: gradle/gradle-build-action@b5126f31dbc19dd434c3269bf8c28c315e121da2 # v2.8.1
                with:
                    arguments: jacocoTestGplayDebugUnitTest
            -   name: Upload failing results
                if: ${{ failure() }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: scripts/uploadReport.sh "${{ secrets.LOG_USERNAME }}" "${{ secrets.LOG_PASSWORD }}" ${{github.event.number}} "test" "Unit" ${{github.event.number}}
            -   name: Upload coverage to codecov
                uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    flags: unit
                    fail_ci_if_error: true
            -   name: Upload jacoco artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
                with:
                    name: test-results
                    path: app/build/reports/tests/testGplayDebugUnitTest/
